"use client";

import { motion } from "framer-motion";
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from "@/components/ui/accordion";

interface FaqEntry {
  question: string;
  answer: string;
  mailtoSubject?: string;
}

const faqs: FaqEntry[] = [
  {
    question: "What is Metadata Reader?",
    answer:
      "Metadata Reader is a free, browser-based tool that lets you extract and read hidden metadata from AI-generated images — including prompts, models, seeds, and generation settings. It also lets you strip all metadata from images before sharing them.",
  },
  {
    question: "Which AI tools are supported?",
    answer:
      "We currently support images generated by Stable Diffusion (A1111) and ComfyUI. We're constantly adding support for new tools, if you want to request a new tool, please contact us at contact@metadata-reader.com",
    mailtoSubject: "Tool support request",
  },
  {
    question: "Is my data private?",
    answer:
      "Yes, 100%. Everything runs entirely in your browser. Your images are never uploaded to any server. No data ever leaves your device.",
  },
  {
    question: "What image formats are supported?",
    answer:
      "We support PNG, JPEG, and WebP files. These are the most common formats used by AI image generators to store metadata.",
  },
  {
    question: "What does 'Clean Metadata' do?",
    answer:
      "The Clean feature strips all embedded metadata (EXIF, GPS, AI generation parameters, etc.) from your images. This is useful when you want to share images without revealing how they were made or any personal information.",
  },
  {
    question: "Why aren't my LoRAs showing up?",
    answer:
      "LoRA detection depends on the node used in your workflow. ComfyUI has many different LoRA loader nodes, and our parser may not support all of them yet. If your LoRAs aren't detected, please contact us at contact@metadata-reader.com with your workflow — we'll add support for your LoRA node.",
    mailtoSubject: "LoRA node support request",
  },
  {
    question: "Why can't I see any metadata in my image?",
    answer:
      "Some tools (like ChatGPT, Google's Nano Banana) don't embed metadata in the image file. Other platforms (like Twitter, Instagram, Discord) automatically strip metadata when you upload an image. We're working on adding support for more tools, if you want to request a new tool, please contact us at contact@metadata-reader.com",
    mailtoSubject: "Tool support request",
  },
  {
    question: "Is Metadata Reader free?",
    answer:
      "Yes, Metadata Reader is completely free to use with no limitations.",
  },
  {
    question: "I have another question, how can I reach you?",
    answer:
      "You can contact us at contact@metadata-reader.com — we'll be happy to help!",
    mailtoSubject: "Question about Metadata Reader",
  },
];

function renderAnswer(text: string, mailtoSubject?: string) {
  return text.split(/([\w.-]+@[\w.-]+\.\w+)/).map((part, i) =>
    /[\w.-]+@[\w.-]+\.\w+/.test(part) ? (
      <a
        key={i}
        href={`mailto:${part}${mailtoSubject ? `?subject=${encodeURIComponent(mailtoSubject)}` : ""}`}
        className="text-primary hover:underline"
      >
        {part}
      </a>
    ) : (
      part
    ),
  );
}

export default function FaqPage() {
  return (
    <div className="bg-background relative">
      <div className="relative z-10 container mx-auto max-w-3xl">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="px-4 py-12 lg:py-16"
        >
          <div className="text-center space-y-4 mb-12">
            <h1 className="font-bold tracking-tighter text-4xl sm:text-5xl bg-clip-text text-transparent bg-gradient-to-r from-primary to-primary/30">
              FAQ
            </h1>
            <p className="text-lg text-muted-foreground max-w-xl mx-auto">
              Everything you need to know about Metadata Reader.
            </p>
          </div>

          <Accordion type="single" collapsible className="space-y-3">
            {faqs.map((faq, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 15 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.4, delay: index * 0.05 }}
              >
                <AccordionItem
                  value={`faq-${index}`}
                  className="border border-border/50 rounded-xl overflow-hidden bg-card"
                >
                  <AccordionTrigger className="px-5 py-4 hover:no-underline cursor-pointer">
                    {faq.question}
                  </AccordionTrigger>
                  <AccordionContent className="px-5 text-muted-foreground leading-relaxed">
                    {renderAnswer(faq.answer, faq.mailtoSubject)}
                  </AccordionContent>
                </AccordionItem>
              </motion.div>
            ))}
          </Accordion>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.5, delay: 0.4 }}
            className="text-center mt-12"
          >
            <p className="text-muted-foreground">
              Still have questions?{" "}
              <a
                href="mailto:contact@metadata-reader.com?subject=Question%20about%20Metadata%20Reader"
                className="text-primary hover:underline"
              >
                Contact us
              </a>
            </p>
          </motion.div>
        </motion.div>
      </div>
    </div>
  );
}
